### PR TITLE
types: improve typing to allow custom request and reply

### LINKED ISSUE #207: Unable to use a Typescript generic for the Params property off of the request
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.13.0

### Plugin version

4.3.0

### Node.js version

18.17.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.0

### Description

I'm trying to use a generic on the `Params` property for a function that's sent to `@fastify/auth`. However, when I do this, I get the following Typescript error:

```
Type '(request: FastifyRequest<{    Params: Partial<GetUserRequestParams>;}>, reply: FastifyReply) => Promise<void>' is not assignable to type 'FastifyAuthFunction | FastifyAuthFunction[]'.
  Type '(request: FastifyRequest<{    Params: Partial<GetUserRequestParams>;}>, reply: FastifyReply) => Promise<void>' is not assignable to type 'FastifyAuthFunction'.
    Types of parameters 'request' and 'request' are incompatible.
      Type 'FastifyRequest<RouteGenericInterface, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<...>>' is not assignable to type 'FastifyRequest<{ Params: Partial<{ userId: string; }>; }, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<...>>'.
        Type 'RouteGenericInterface' is not assignable to type '{ Params: Partial<{ userId: string; }>; }'.
          Types of property 'Params' are incompatible.
            Type 'unknown' is not assignable to type 'Partial<{ userId: string; }>'.ts(2322)
```

I'm unsure if this is a bug or I'm doing this incorrectly.

### Steps to Reproduce

Below is a snippet of what I'm doing:

```ts
import { 
  FastifyInstance,
  FastifyReply,
  FastifyRequest, 
} from 'fastify';
import { Static, Type } from '@sinclair/typebox';

const GetUserRequestParamsSchema = Type.Object({
  userId: Type.String(),
});

type GetUserRequestParams = Static<typeof GetUserRequestParamsSchema>;

const usersMutationAccessPolicy =
  (fastify: FastifyInstance) =>
  async (
    // Looking to extend Params so Typescript knows about `userId` (below)
    request: FastifyRequest<{
      Params: Partial<GetUserRequestParams>;
    }>,
    reply: FastifyReply,
  ): Promise<void> => {
    const { user } = request.identity;
    // Without extending request.params, it thinks the type is unknown
    const isOwner = user?.id === request.params.userId;

    // do more work below
  }

// Leaving out app startup code to keep this concise

export async function usersController(fastify: FastifyInstance): Promise<void> {
  fastify.patch<{
    Params: UserParams;
    Body: UserPatchBody;
  }>(
    `/:userId`,
    {
      schema: { ... },
      // Getting TS error 
      onRequest: fastify.auth([usersMutationAccessPolicy(fastify)]),
    },
    async (req, res) => {
      const user = await doPatchStuffWithUser();
      res.send(user);
    },
  );
}
```

Something to note. If I just added `usersMutationAccessPolicy(fastify)` to the `onRequest` directly, everything works as expected. Example:

```ts
export async function usersController(fastify: FastifyInstance): Promise<void> {
  fastify.patch<{
    Params: UserParams;
    Body: UserPatchBody;
  }>(
    `/:userId`,
    {
      schema: { ... },
      // Works as expected 
      onRequest: usersMutationAccessPolicy(fastify),
    },
    async (req, res) => {
      const user = await doPatchStuffWithUser();
      res.send(user);
    },
  );
}
```

However, I'm looking to use `@fastify/auth` to compose more access policy functions.

### Expected Behavior

I don't receive any TS error when using

`onRequest: fastify.auth([usersMutationAccessPolicy(fastify)]),` from above.

### PR DESCRIPTION
**Pull request by Puppo**
This PR closes #207 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

File: types/index.d.ts [hunk 1]
```diff
@@ -1,18 +1,21 @@
...
   preHandlerHookHandler
 } from 'fastify';
 
 declare module 'fastify' {
   interface FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider> {
-    auth(
-      functions: fastifyAuth.FastifyAuthFunction[] | (fastifyAuth.FastifyAuthFunction | fastifyAuth.FastifyAuthFunction[])[],
+    auth<
+      Request extends FastifyRequest = FastifyRequest,
+      Reply extends FastifyReply = FastifyReply
```
Comment (Uzlopak) [inline types/index.d.ts:16]: Hmm, looks not correct. Why is Request and Reply not depending on the Generic Types from FastifyInstance?

```suggestion
      Request extends FastifyRequest = Request extends FastifyRequest = FastifyRequest<RawServerDefault, RawRequest, FastifySchema, TypeProvider, ContextConfigDefault, Logger>,
      Reply extends FastifyReply = FastifyReply<RawServer, RawRequest, RawReply, RouteGenericInterface, ContextConfigDefault, FastifySchema, TypeProvider>
```

Untested but I would expect this.

**Review by Uzlopak — DISMISSED** [review]
Please check my comment.

File: types/index.d.ts (hunk 1 above)
Comment (Puppo) [reply types/index.d.ts:16]: The `FastifyRequest` and `FastifyReply` interfaces have changed from your example.
The default should be equal to the old value to prevent breaking the previous code.
Furthermore,  now the `FastifyRequest` accepts other generic types, for instance, RouteGeneric, and in this way, the users can pass the request as they prefer.
If you take a look at the tests, I tried to break nothing and include your request to leave the power to the user to choose the request type.

**Comment by hershmire** [comment]
@Puppo thanks for the PR!

@mcollina @Uzlopak any resolution on this?

**Comment by Puppo** [comment]
@Uzlopak any news on this one? otherwise Matteo cannot merge the PR.

**Comment by Uzlopak** [comment]
@fastify/typescript 

Can somebody else have a look at it. I dont want to be a blocker, but I dont think that the arguments are valid as the generic types are not passed down to the FastifyReply and FastifyRequest.

**Comment by climba03003** [comment]
> I dont think that the arguments are valid as the generic types are not passed down to the FastifyReply and FastifyRequest.

That is true, but most of the time people use only the default server then it would be fine.
It worth a trial how it impact.

**Comment by Uzlopak** [comment]
@mcollina 

Somebody has to decide if this gets merged and published or not.
