### PR TITLE
fix clean status code modified in handler

### LINKED ISSUE #56: statusCode dirty with relation or
## 🐛 Bug Report

An auth "pipeline" could dirty the `reply` status code and when the handler execute, the status code returned is in an bad status.

## To Reproduce

```js
const fastify = require('fastify')()

function authFactory (id, status) {
  return function (request, reply, done) {
    console.log(id)
    if (request.query.name === id || request.query.name === 'all') {
      done()
    } else {
      reply.code(status)
      done(new Error('query ' + id))
    }
  }
}

fastify.register(require('fastify-auth'))
  .after(() => {
    fastify.addHook('preHandler', fastify.auth([authFactory('one', 501), authFactory('two', 502)], { relation: 'or' }))
    fastify.get('/', (req, res) => res.send(42))
  })

fastify.listen(3000)
```

## Expected behavior

Calling `curl -X GET 'http://localhost:3000/?name=two'` I would expect 200 but I receive `501` that was set by the first auth handler that has dirtier the `replay`, I think we should restore the status code across the auth handler execution.

```js
$ curl -v http://localhost:3000?name=two
*   Trying ::1:3000...
* TCP_NODELAY set
*   Trying 127.0.0.1:3000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /?name=two HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.65.3
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 501 Not Implemented
< content-type: application/json; charset=utf-8
< content-length: 2
< Connection: keep-alive
<
42
```

## Your Environment

- *node version*: 12
- *fastify version*: >=2.8.0
- *os*: Windows
- *any other relevant information*

### PR DESCRIPTION
**Pull request by Eomm**
Fixes #56 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: fastify-auth.js [hunk 1]
```diff
@@ -83,6 +83,9 @@ function auth (functions, options) {
           return that.nextAuth(err)
         }
 
+        if (that.i > 0 && that.reply.res.statusCode && that.reply.res.statusCode >= 400) {
+          that.reply.res.statusCode = 200
+        }
```
Comment (mcollina) [inline fastify-auth.js]: Why not using `that.reply.code(200)`?

Comment (Eomm) [reply fastify-auth.js]: Not a reason
Fixed
